// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/sync/syncpb/sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentIDRequest) Reset() {
	*x = DocumentIDRequest{}
	mi := &file_internal_sync_syncpb_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIDRequest) ProtoMessage() {}

func (x *DocumentIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sync_syncpb_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIDRequest.ProtoReflect.Descriptor instead.
func (*DocumentIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_sync_syncpb_sync_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PermissionChangedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionChangedRequest) Reset() {
	*x = PermissionChangedRequest{}
	mi := &file_internal_sync_syncpb_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionChangedRequest) ProtoMessage() {}

func (x *PermissionChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sync_syncpb_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionChangedRequest.ProtoReflect.Descriptor instead.
func (*PermissionChangedRequest) Descriptor() ([]byte, []int) {
	return file_internal_sync_syncpb_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionChangedRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *PermissionChangedRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PermissionChangedRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_internal_sync_syncpb_sync_proto protoreflect.FileDescriptor

const file_internal_sync_syncpb_sync_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/sync/syncpb/sync.proto\x12\n" +
	"syncserver\x1a\x1bgoogle/protobuf/empty.proto\"#\n" +
	"\x11DocumentIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"^\n" +
	"\x18PermissionChangedRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\xfd\x01\n" +
	"\x12SyncServerInternal\x12G\n" +
	"\fPostSnapshot\x12\x1d.syncserver.DocumentIDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x0eDeleteDocument\x12\x1d.syncserver.DocumentIDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"\x11PermissionChanged\x12$.syncserver.PermissionChangedRequest\x1a\x16.google.protobuf.Empty\"\x00B4Z2collaborative-markdown-editor/internal/sync/syncpbb\x06proto3"

var (
	file_internal_sync_syncpb_sync_proto_rawDescOnce sync.Once
	file_internal_sync_syncpb_sync_proto_rawDescData []byte
)

func file_internal_sync_syncpb_sync_proto_rawDescGZIP() []byte {
	file_internal_sync_syncpb_sync_proto_rawDescOnce.Do(func() {
		file_internal_sync_syncpb_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_sync_syncpb_sync_proto_rawDesc), len(file_internal_sync_syncpb_sync_proto_rawDesc)))
	})
	return file_internal_sync_syncpb_sync_proto_rawDescData
}

var file_internal_sync_syncpb_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_sync_syncpb_sync_proto_goTypes = []any{
	(*DocumentIDRequest)(nil),        // 0: syncserver.DocumentIDRequest
	(*PermissionChangedRequest)(nil), // 1: syncserver.PermissionChangedRequest
	(*emptypb.Empty)(nil),            // 2: google.protobuf.Empty
}
var file_internal_sync_syncpb_sync_proto_depIdxs = []int32{
	0, // 0: syncserver.SyncServerInternal.PostSnapshot:input_type -> syncserver.DocumentIDRequest
	0, // 1: syncserver.SyncServerInternal.DeleteDocument:input_type -> syncserver.DocumentIDRequest
	1, // 2: syncserver.SyncServerInternal.PermissionChanged:input_type -> syncserver.PermissionChangedRequest
	2, // 3: syncserver.SyncServerInternal.PostSnapshot:output_type -> google.protobuf.Empty
	2, // 4: syncserver.SyncServerInternal.DeleteDocument:output_type -> google.protobuf.Empty
	2, // 5: syncserver.SyncServerInternal.PermissionChanged:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_sync_syncpb_sync_proto_init() }
func file_internal_sync_syncpb_sync_proto_init() {
	if File_internal_sync_syncpb_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sync_syncpb_sync_proto_rawDesc), len(file_internal_sync_syncpb_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_sync_syncpb_sync_proto_goTypes,
		DependencyIndexes: file_internal_sync_syncpb_sync_proto_depIdxs,
		MessageInfos:      file_internal_sync_syncpb_sync_proto_msgTypes,
	}.Build()
	File_internal_sync_syncpb_sync_proto = out.File
	file_internal_sync_syncpb_sync_proto_goTypes = nil
	file_internal_sync_syncpb_sync_proto_depIdxs = nil
}
