// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: internal/sync/syncpb/sync.proto

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SyncServerInternal_GetState_FullMethodName          = "/syncserver.SyncServerInternal/GetState"
	SyncServerInternal_DeleteDocument_FullMethodName    = "/syncserver.SyncServerInternal/DeleteDocument"
	SyncServerInternal_PermissionChanged_FullMethodName = "/syncserver.SyncServerInternal/PermissionChanged"
)

// SyncServerInternalClient is the client API for SyncServerInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncServerInternalClient interface {
	GetState(ctx context.Context, in *DocumentIDRequest, opts ...grpc.CallOption) (*DocumentStateResponse, error)
	DeleteDocument(ctx context.Context, in *DocumentIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PermissionChanged(ctx context.Context, in *PermissionChangedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type syncServerInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServerInternalClient(cc grpc.ClientConnInterface) SyncServerInternalClient {
	return &syncServerInternalClient{cc}
}

func (c *syncServerInternalClient) GetState(ctx context.Context, in *DocumentIDRequest, opts ...grpc.CallOption) (*DocumentStateResponse, error) {
	out := new(DocumentStateResponse)
	err := c.cc.Invoke(ctx, SyncServerInternal_GetState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServerInternalClient) DeleteDocument(ctx context.Context, in *DocumentIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SyncServerInternal_DeleteDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServerInternalClient) PermissionChanged(ctx context.Context, in *PermissionChangedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SyncServerInternal_PermissionChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServerInternalServer is the server API for SyncServerInternal service.
// All implementations must embed UnimplementedSyncServerInternalServer
// for forward compatibility
type SyncServerInternalServer interface {
	GetState(context.Context, *DocumentIDRequest) (*DocumentStateResponse, error)
	DeleteDocument(context.Context, *DocumentIDRequest) (*emptypb.Empty, error)
	PermissionChanged(context.Context, *PermissionChangedRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSyncServerInternalServer()
}

// UnimplementedSyncServerInternalServer must be embedded to have forward compatible implementations.
type UnimplementedSyncServerInternalServer struct {
}

func (UnimplementedSyncServerInternalServer) GetState(context.Context, *DocumentIDRequest) (*DocumentStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedSyncServerInternalServer) DeleteDocument(context.Context, *DocumentIDRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedSyncServerInternalServer) PermissionChanged(context.Context, *PermissionChangedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermissionChanged not implemented")
}
func (UnimplementedSyncServerInternalServer) mustEmbedUnimplementedSyncServerInternalServer() {}

// UnsafeSyncServerInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServerInternalServer will
// result in compilation errors.
type UnsafeSyncServerInternalServer interface {
	mustEmbedUnimplementedSyncServerInternalServer()
}

func RegisterSyncServerInternalServer(s grpc.ServiceRegistrar, srv SyncServerInternalServer) {
	s.RegisterService(&SyncServerInternal_ServiceDesc, srv)
}

func _SyncServerInternal_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServerInternalServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncServerInternal_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServerInternalServer).GetState(ctx, req.(*DocumentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncServerInternal_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServerInternalServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncServerInternal_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServerInternalServer).DeleteDocument(ctx, req.(*DocumentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncServerInternal_PermissionChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionChangedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServerInternalServer).PermissionChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncServerInternal_PermissionChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServerInternalServer).PermissionChanged(ctx, req.(*PermissionChangedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncServerInternal_ServiceDesc is the grpc.ServiceDesc for SyncServerInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncServerInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncserver.SyncServerInternal",
	HandlerType: (*SyncServerInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _SyncServerInternal_GetState_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _SyncServerInternal_DeleteDocument_Handler,
		},
		{
			MethodName: "PermissionChanged",
			Handler:    _SyncServerInternal_PermissionChanged_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/sync/syncpb/sync.proto",
}
